apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  labels:
    name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: {{ .Values.serviceName }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
      - name: {{ .Values.serviceName }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.servicePort }}
          protocol: TCP
