apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.serviceName }}
spec:
  ports:
  - port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.servicePort }}
  selector:
    name: {{ .Values.serviceName }}
  sessionAffinity: None
  type: ClusterIP

