apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ .Values.serviceName }}-ingress
  namespace: {{ .Values.serviceName }}
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.serviceName }}
              servicePort: {{ .Values.servicePort }}
            path: /
  tls:
      - hosts:
          - {{ .Values.hostname }}
        secretName: {{ .Values.tlsSecretName }}